### ISSUE TITLE
Stratification and Visualization

### ISSUE THREAD

**Issue by Jeff87075** [ghar1821/TrackSOM#1]
Hi, I wanted to ask a few things regarding the analysis and also visualization:

1) If my data contains samples from different groups, say I have males vs females, how can I incorporate this stratification into the analysis (or maybe how can I stratify them in the presentation/visualization)? I don't want to split the samples before running the TrackSOM algorithm because I want the clusters and meta-clusters to be the same for easier comparison instead of having two different clustering maps. 

2) For visualization, is there any way to visualize the SOM itself (like a more traditional tSNE/UMAP plot) for a more intuitive view of the distribution of markers before going into the network plot to visualize the temporal evolution? 

3) How can I subset certain populations (such as lower half of Figure 8 in the manuscript only looking at infiltrating macrophages) and then visualizing the density of other biomarkers? 

Thanks a lot for the great package!

**Comment by ghar1821** [comment]
Hi there,

Thank you very much for your interest in the package! 

1. Unfortunately, the current network plot or the timeseries heatmap does not automatically stratify the data based on groups. However, what you can do is upon running the TrackSOM algorithm, split the result into 2 different data.table, 1 containing only data for male, the other only for female, and pass each data into the network plot or timeseries heatmap function. That way you can compare the groups side by side as each group will result in its own plot. However, it is possible for the layout of the network plot to vary between the groups as the layout is automatically calculated by the igraph package based on the data you have. If it is paramount to maintain a consistent layout, I suggest you use the timeseries heatmap and supply a custom ordering for the meta-clusters (optional).
2. The package unfortunately does not have the ability to visualise the SOM nodes as traditional UMAP. However, may I direct you to the Spectre package (https://github.com/ImmuneDynamics/Spectre) co-developed by myself with 2 other colleagues which shall allow you to plot the SOM membership as tSNE/UMAP plots? You can store the TrackSOM results as data.table and pass that to the Spectre package to draw up the plots.
3. You can first determine which meta-clusters represents certain population, then filter out the data.table result (produced by TrackSOM) to only contain those meta-clusters, then draw the plots. 

Let me know how you go!
